events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream frontend_server {
        server frontend:3000;
    }

    upstream backend_server {
        server backend:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://backend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
